apps/adm/urls.py
# -*- coding: UTF-8 -*-
# __author__ : RobbieHan
# __data__  : 2017/12/8

from django.conf.urls import url

from adm import views_bsm, views_equipment

urlpatterns = [

    # 基础管理：供应商管理，品牌管理，资产类型管理
    url(r'supplier/$', views_bsm.SupplierView.as_view(), name="supplier"),
    url(r'supplier/list', views_bsm.SupplierListView.as_view(), name="supplier-list"),
    url(r'supplier/detail', views_bsm.SupplierDetailView.as_view(), name="supplier-detail"),
    url(r'supplier/delete', views_bsm.SupplierDeleteView.as_view(), name="supplier-delete"),

    url(r'assettype/$', views_bsm.AssetTypeView.as_view(), name="assettype"),
    url(r'assettype/list', views_bsm.AssetTypeListView.as_view(), name="assettype-list"),
    url(r'assettype/detail', views_bsm.AssetTypeDetailView.as_view(), name="assettype-detail"),
    url(r'assettype/delete', views_bsm.AssetTypeDeleteView.as_view(), name="assettype-delete"),

    url(r'customer/$', views_bsm.CustomerView.as_view(), name="customer"),
    url(r'customer/list', views_bsm.CustomerListView.as_view(), name="customer-list"),
    url(r'customer/detail', views_bsm.CustomerDetailView.as_view(), name="customer-detail"),
    url(r'customer/delete', views_bsm.CustomerDeleteView.as_view(), name="customer-delete"),

    url(r'equipmenttype/$', views_bsm.EquipmentTypeView.as_view(), name="equipmenttype"),
    url(r'equipmenttype/list', views_bsm.EquipmentTypeListView.as_view(), name="equipmenttype-list"),
    url(r'equipmenttype/detail', views_bsm.EquipmentTypeDetailView.as_view(), name="equipmenttype-detail"),
    url(r'equipmenttype/delete', views_bsm.EquipmentTypeDeleteView.as_view(), name="equipmenttype-delete"),

]

extra_apps/DjangoUeditor/urls.py
# coding:utf-8
from django import VERSION
from .widgets import UEditorWidget, AdminUEditorWidget
from .views import get_ueditor_controller
from django.conf.urls import url

urlpatterns = [
    url(r'^controller/$', get_ueditor_controller),
]

gistandard/urls.py
from django.conf.urls import url, include
from django.views.static import serve
from gistandard.settings import MEDIA_ROOT

import xadmin

from users.views_user import LoginView, IndexView, LogoutView
from system.views import SystemView
from adm.views import AdmView
from personal import views as personal_views
from personal import views_work_order as order

urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    url(r'^media/(?P<path>.*)$', serve, {"document_root": MEDIA_ROOT}),
    url(r'^$', IndexView.as_view(), name='index'),
    # 用户登录
    url(r'^login/$', LoginView.as_view(), name='login'),
    url(r'^logout/$', LogoutView.as_view(), name="logout"),

    url(r'^system/$', SystemView.as_view(), name="system"),
    url(r'^system/basic/', include('users.urls', namespace='system-basic')),
    url(r'^system/rbac/', include('rbac.urls', namespace='system-rbac')),
    url(r'^system/tools/', include('system.urls', namespace='system-tools')),

    url(r'^adm/$', AdmView.as_view(), name="adm-main"),
    url(r'^adm/bsm/', include('adm.urls', namespace='adm-bsm')),
    url(r'^adm/equipment/', include('adm.urls_equipment', namespace='adm-equipment')),
    url(r'^adm/asset/', include('adm.urls_asset', namespace='adm-asset')),

    url(r'^personal/$', personal_views.PersonalView.as_view(), name="personal"),
    url(r'^personal/userinfo', personal_views.UserInfoView.as_view(), name="personal-user_info"),
    url(r'^personal/uploadimage', personal_views.UploadImageView.as_view(), name="personal-uploadimage"),
    url(r'^personal/passwordchange', personal_views.PasswdChangeView.as_view(), name="personal-passwordchange"),
    url(r'^personal/phonebook', personal_views.PhoneBookView.as_view(), name="personal-phonebook"),
    url(r'^personal/workorder_Icrt/$', order.WorkOrderView.as_view(), name="personal-workorder_Icrt"),
    url(r'^personal/workorder_Icrt/list', order.WorkOrderListView.as_view(), name="personal-workorder-list"),
    url(r'^personal/workorder_Icrt/create', order.WorkOrderCreateView.as_view(), name="personal-workorder-create"),
    url(r'^personal/workorder_Icrt/detail', order.WorkOrderDetailView.as_view(), name="personal-workorder-detail"),
    url(r'^personal/workorder_Icrt/delete', order.WorkOrderDeleteView.as_view(), name="personal-workorder-delete"),
    url(r'^personal/workorder_Icrt/update', order.WorkOrderUpdateView.as_view(), name="personal-workorder-update"),
    url(r'^personal/workorder_app/$', order.WorkOrderView.as_view(), name="personal-workorder_app"),
    url(r'^personal/workorder_app/send', order.WrokOrderSendView.as_view(), name="personal-workorder-send"),
    url(r'^personal/workorder_rec/$', order.WorkOrderView.as_view(), name="personal-workorder_rec"),
    url(r'^personal/workorder_rec/execute', order.WorkOrderExecuteView.as_view(), name="personal-workorder-execute"),
    url(r'^personal/workorder_rec/finish', order.WorkOrderFinishView.as_view(), name="personal-workorder-finish"),
    url(r'^personal/workorder_rec/upload', order.WorkOrderUploadView.as_view(), name="personal-workorder-upload"),
    url(r'^personal/workorder_rec/return', order.WorkOrderReturnView.as_view(), name="personal-workorder-return"),
    url(r'^personal/workorder_Icrt/upload', order.WorkOrderProjectUploadView.as_view(),
        name="personal-workorder-project-upload"),
    url(r'^personal/workorder_all/$', order.WorkOrderView.as_view(), name="personal-workorder_all"),
    url(r'^personal/document/$', order.WorkOrderDocumentView.as_view(), name="personal-document"),
    url(r'^personal/document/list', order.WorkOrderDocumentListView.as_view(), name="personal-document-list"),

]

apps/adm/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Supplier(models.Model):
    """
    分销商管理
    """
    company = models.CharField(max_length=30, verbose_name="公司名称")
    address = models.CharField(max_length=100, verbose_name="地址")
    linkname = models.CharField(max_length=20, verbose_name="联系人")
    phone = models.CharField(max_length=20, verbose_name="联系电话")
    status = models.BooleanField(default=True, verbose_name="状态")
    belongs_to = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL, verbose_name="责任人")
    desc = models.TextField(blank=True, null=True, verbose_name="备注")
    add_time = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")

    class Meta:
        verbose_name = "分销商管理"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.company


class Customer(models.Model):
    """
    客户信息
    """
    unit = models.CharField(max_length=50, verbose_name="客户单位")
    address = models.CharField(max_length=100, verbose_name="地址")
    name = models.CharField(max_length=20, verbose_name="联系人")
    phone = models.CharField(max_length=30, verbose_name="联系电话")
    belongs_to = models.ForeignKey(User, blank=True, null=True , on_delete=models.SET_NULL, verbose_name="责任人")
    status = models.BooleanField(default=True, verbose_name="状态")
    desc = models.TextField(blank=True, null=True, verbose_name="备注")
    add_time = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")

    class Meta:
        verbose_name = "客户管理"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.unit


class AssetType(models.Model):
    """
    资产类型
    """
    name = models.CharField(max_length=30, verbose_name="类型名称", help_text="类型名称")
    desc = models.TextField(blank=True, null=True, verbose_name="备注")


    class Meta:
        verbose_name = "资产类型"

    def __str__(self):
        return self.name


class Asset(models.Model):
    asset_status = (
        ("0", "闲置"),
        ("1", "在用"),
        ("2", "维修"),
        ("3", "报废"),
        ("4", "售出")
    )
    warehouse_choices = (
        ("0", "南京"),
        ("1", "苏州"),
    )
    assetNum = models.CharField(max_length=128, default="", verbose_name="资产编号")
    assetType = models.ForeignKey(AssetType, blank=True, null=True, on_delete=models.SET_NULL, verbose_name="资产类型")
    brand = models.CharField(max_length=20, blank=True, null=True, verbose_name="品牌")
    model = models.CharField(max_length=30, default="", verbose_name="型号")
    warehouse = models.CharField(choices=warehouse_choices, default="1", max_length=20, verbose_name="仓库")
    price = models.IntegerField(blank=True, null=True, verbose_name="价格")
    buyDate = models.DateField(verbose_name="购买日期")
    warrantyDate = models.DateField(verbose_name="到保日期")
    status = models.CharField(choices=asset_status, max_length=20, default="1", verbose_name="资产状态")
    customer = models.CharField(max_length=80, default="", blank=True, null=True, verbose_name="客户信息")
    owner = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL, verbose_name="使用人")
    operator = models.CharField(max_length=20, default="", verbose_name="入库人")
    add_time = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")
    desc = models.TextField(default="", blank=True, null=True, verbose_name="备注信息")

    class Meta:
        verbose_name = "资产管理"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.assetNum


class AssetFile(models.Model):
    asset = models.ForeignKey(Asset, blank=True, null=True, on_delete=models.SET_NULL, verbose_name="资产")
    upload_user = models.CharField(max_length=20, verbose_name="上传人")
    file_content = models.ImageField(upload_to="asset_file/%Y/%m", null=True, blank=True, verbose_name="资产文件")
    add_time = models.DateTimeField(auto_now_add=True, verbose_name="上传时间")


class AssetLog(models.Model):
    asset = models.ForeignKey(Asset, verbose_name="资产")
    operator = models.CharField(max_length=20, verbose_name="操作人")
    desc = models.TextField(default="", verbose_name="备注")
    add_time = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")

    class Mate:
        verbose_name = "变更记录"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.asset


class ServiceInfo(models.Model):
    content = models.TextField(verbose_name="记录内容")
    writer = models.ForeignKey(User, blank=True, null=True, on_delete=models.SET_NULL, verbose_name="记录人")
    is_reminding = models.BooleanField(default=False, verbose_name="邮件消息提醒")
    add_time = models.DateTimeField(auto_now_add=True, verbose_name="添加时间")

    class Mate:
        verbose_name = "服务记录"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.content


class EquipmentType(models.Model):
    """
    设备类型
    """
    name = models.CharField(max_length=30, verbose_name="类型名称", help_text="类型名称")
    desc = models.TextField(blank=True, null=True, verbose_name="备注")

    class Meta:
        verbose_name = "设备类型"
        verbose_name_plural = verbose_name
        ordering = ['id']

    def __str__(self):
        return self.name


class Equipment(models.Model):
    number = models.CharField(max_length=30, default="", verbose_name="设备编号")
    equipment_type = models.ForeignKey(EquipmentType, blank=True, null=True, on_delete=models.SET_NULL, verbose_name="设备类型")
    equipment_model = models.CharField(max_length=50, default="", verbose_name="设备型号")
    buy_date = models.DateField(verbose_name="购买日期")
    warranty_date = models.DateField(verbose_name="质保日期")
    accounting = models.BooleanField(default=False, verbose_name="费用核算状态")
    config_desc = models.TextField(blank=True, null=True, verbose_name="配置说明")
    customer = models.ForeignKey(Customer, blank=True, null=True, on_delete=models.SET_NULL, verbose_name="客户信息")
    supplier = models.ForeignKey(Supplier, blank=True, null=True, on_delete=models.SET_NULL, verbose_name="分销商")
    service_info = models.ManyToManyField(ServiceInfo, blank=True, verbose_name="服务记录")

    class Meta:
        verbose_name = "设备管理"
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.number

apps/adm/forms.py
# -*- coding: UTF-8 -*-
# __author__ : RobbieHan
# __data__  : 2017/12/20

from django import forms
from .models import Supplier, AssetType, Customer, EquipmentType, Equipment, Asset, AssetFile


class SupplierCreateForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = '__all__'
        error_messages = {
            "company": {"required": "请输入分销商公司名称"},
            "address": {"required": "请输入分销商公司地址"},
            "linkname": {"required": "请输入分销商联系人"},
            "phone": {"required": "请输入分销商联系电话"}
        }

    def clean(self):
        cleaned_data = super(SupplierCreateForm, self).clean()
        company = cleaned_data.get("company")
        if Supplier.objects.filter(company=company).count():
            raise forms.ValidationError('分销商："{}"已存在'.format(company))


class SupplierUpdateForm(forms.ModelForm):
    class Meta:
        model = Supplier
        fields = '__all__'
        error_messages = {
            "company": {"required": "请输入分销商公司名称"},
            "address": {"required": "请输入分销商公司地址"},
            "linkname": {"required": "请输入分销商联系人"},
            "phone": {"required": "请输入分销商联系电话"}
        }


class AssetTypeForm(forms.ModelForm):
    class Meta:
        model = AssetType
        fields = '__all__'


class CustomerCreateForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['unit', 'address', 'name', 'phone', 'status', 'belongs_to', 'desc']
        error_messages = {
            "unit": {"required": "请填写客户单位"},
            "address": {"required": "请填写客户单位地址"},
            "name": {"required": "请填写客户联系人"},
            "phone": {"required": "请填写客户联系电话"}
        }

    def clean(self):
        cleaned_data = super(CustomerCreateForm, self).clean()
        unit = cleaned_data.get("unit")
        if Customer.objects.filter(unit=unit).count():
            raise forms.ValidationError('客户单位："{}"已经存在'.format(unit))


class CustomerUpdateForm(forms.ModelForm):
    class Meta:
        model = Customer
        fields = ['unit', 'address', 'name', 'phone', 'status', 'belongs_to', 'desc']
        error_messages = {
            "unit": {"required": "请填写客户单位"},
            "address": {"required": "请填写客户单位地址"},
            "name": {"required": "请填写客户联系人"},
            "phone": {"required": "请填写客户联系电话"}
        }


class EquipmentTypeForm(forms.ModelForm):
    class Meta:
        model = EquipmentType
        fields = '__all__'


class EquipmentCreateForm(forms.ModelForm):

    class Meta:
        model = Equipment
        fields = '__all__'
        error_messages = {
            "number": {"required": "设备编号不能为空"},
            "equipment_model": {"required": "请输入设备型号"},
            "buy_date": {"required": "请输入购买日期"},
            "warranty_date": {"required": "请输入质保日期"},
            "supplier": {"required": "请选择分销商"}
        }

    def clean(self):
        cleaned_data = super(EquipmentCreateForm, self).clean()
        number = cleaned_data.get("number")
        if Equipment.objects.filter(number=number).count():
            raise forms.ValidationError('设备编号：{}已存在'.format(number))


class EquipmentUpdateForm(forms.ModelForm):

    class Meta:
        model = Equipment
        # fields = '__all__'
        # 排除 service_info字段，不然通过modelform更新数据时，m2m数据会丢失
        exclude = ['service_info', ]
        error_messages = {
            "number": {"required": "设备编号不能为空"},
            "equipment_model": {"required": "请输入设备型号"},
            "buy_date": {"required": "请输入购买日期"},
            "warranty_date": {"required": "请输入质保日期"},
            "supplier": {"required": "请选择分销商"}
        }


class AssetCreateForm(forms.ModelForm):
    class Meta:
        model = Asset
        fields = '__all__'
        error_messages = {
            "assetNum": {"required": "资产编号不能为空"},
            "model": {"required": "请输入资产型号"},
            "buyDate": {"required": "请输入购买日期"},
            "warrantyDate": {"required": "请输入质保日期"},
            "status": {"required": "请选择资产状态"}
        }

    def clean(self):
        cleaned_data = super(AssetCreateForm, self).clean()
        number = cleaned_data.get("assetNum")
        if Asset.objects.filter(assetNum=number).count():

            raise forms.ValidationError('资产编号：{}已存在'.format(number))

class AssetUpdateForm(forms.ModelForm):
    class Meta:
        model = Asset
        fields = '__all__'
        error_messages = {
            "assetNum": {"required": "资产编号不能为空"},
            "model": {"required": "请输入资产型号"},
            "buyDate": {"required": "请输入购买日期"},
            "warrantyDate": {"required": "请输入质保日期"},
            "status": {"required": "请选择资产状态"}
        }


class AssetUploadForm(forms.ModelForm):
    class Meta:
        model = AssetFile
        fields = '__all__'

apps/adm/views.py
from django.shortcuts import render
from django.views.generic.base import View

from utils.mixin_utils import LoginRequiredMixin
from rbac.models import Menu
from system.models import SystemSetup

class AdmView(LoginRequiredMixin, View):
    """
    行政
    """
    def get(self, request):
        ret = Menu.getMenuByRequestUrl(url=request.path_info)
        ret.update(SystemSetup.getSystemSetupLastData())
        return render(request, 'adm/adm_index.html', ret)

templates/adm/asset/asset_detail.html
{% extends "base-left.html" %}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" href="{% static 'js/plugins/layer/skin/layer.css' %}">
{% endblock %}

{% block content %}

<!-- Content Header (Page header) -->
<section class="content-header margin-bottom">
  <ol class="breadcrumb">
    <li><a href=""><i class="fa fa-dashboard"></i>办公平台</a></li>
    <li class="active"><a href="#">资产管理</a></li>
    <li class="active"><a href="#">资产详情</a></li>
  </ol>
</section>
    <!-- Main content -->

  <section class="content">
      <div class="row">
       <div class="col-md-12">
        <div class="box box-primary">
            <div class="box-header with-border">
              <h3 class="box-title">资产详情</h3>

              <div class="box-tools">
                <button type="button" class="btn btn-box-tool" data-widget="collapse"><i class="fa fa-minus"></i>
                </button>
              </div>
            </div>
            <div class="box-body no-padding">
                <div class="btn-group pull-right margin-b-10 margin-r-5">
                <button type="button" class="btn btn-default btn-sm" onclick="doAssetUpload({{ asset.id }})">
                  <i class="fa fa-cloud-upload">上传资料</i>
                </button>
                  <button type="button" class="btn btn-primary btn-sm" title="返回" id="btnReturn">
                      <i class="fa fa-undo"> 返回</i>
                  </button>
                  <button type="button" class="btn btn-info btn-sm" title="编辑" id="doUpdate"
                          onclick="doUpdate({{ asset.id }})">
                      <i class="fa fa-pencil"> 编辑</i>
                  </button>
                </div>
           </div>

               <div class="table-responsive mailbox-messages">
                  <table class="table" id="tbWorkList"  style="white-space: nowrap;">
                    <tbody>
                        <tr class="info">
                            <td width="10%"><strong>资产编号</strong></td>
                            <td class="text-left">{{ asset.assetNum }}</td>
                            <td width="10%"><strong>类型</strong></td>
                            <td class="text-left">{{ asset.assetType }}</td>
                        </tr>
                        <tr>
                            <td><strong>品牌</strong></td>
                            <td>{{ asset.brand }}</td>
                            <td><strong>型号</strong></td>
                            <td>{{ asset.model }}</td>
                        </tr>
                        <tr class="info">
                            <td><strong>仓库</strong></td>
                            <td>{{ asset.get_warehouse_display }}</td>
                            <td><strong>状态</strong></td>
                            <td>{{ asset.get_status_display }}</td>
                        </tr>
                        <tr>
                            <td><strong>购买日期</strong></td>
                            <td>{{ asset.buyDate }}</td>
                            <td><strong>质保日期</strong></td>
                            <td>{{ asset.warrantyDate }}</td>
                        </tr>
                        <tr class="info">
                            <td><strong>价格/元</strong></td>
                            <td>{{ asset.price | default_if_none:"" }}</td>
                            <td><strong>责任人</strong></td>
                            <td>{{ asset.owner.name }}</td>
                        </tr>
                        <tr>
                            <td><strong>入库人</strong></td>
                            <td>{{ asset.operator }}</td>
                            <td><strong>入库时间</strong></td>
                            <td>{{ asset.add_time }}</td>
                        </tr>
                        <tr class="info">
                            <td><strong>客户信息</strong></td>
                            <td colspan="3" >{{ asset.customer | default_if_none:"" }}</td>
                        </tr>
                        <tr>
                            <td><strong>备注</strong></td>
                            <td colspan="3" >{{ asset.desc }}</td>
                        </tr>
                    </tbody>
                  </table>
                </div>
               <br>
               <div class="box-footer">
                  <ul class="mailbox-attachments clearfix">
                    {% for file in asset_file %}
                    <li>
                      <a href="/media/{{ file.file_content }}" target="_blank">
                        <span class="mailbox-attachment-icon has-img"><img src="/media/{{file.file_content }}" alt=""></span>
                      </a>

                      <div class="mailbox-attachment-info">
                        <a href="/media/{{ file.file_content }}" target="_blank"><i class="fa fa-camera"></i> <small>{{ file.file_content|cut:'asset_file' }}</small></a>
                            <span class="mailbox-attachment-size">
                              <b>上传人</b>：{{ file.upload_user }}
                              <a href="/media/{{ file.file_content }}" download="{{ file.file_content }}" class="btn btn-default btn-xs pull-right"><i class="fa fa-cloud-download"></i></a>
                            </span>
                      </div>
                    </li>
                   {% endfor %}
                  </ul>
                </div>
            <!-- /.box-footer -->
            </div>
            <!-- /.box-body -->
          </div>
      </div>
        <!-- /.col -->
     <!-- TO DO List -->
      <div class="box">
        <div class="box-header">
          <i class="ion ion-clipboard"></i>
          <h3 class="box-title">资产变更记录</h3>
        </div>
        <!-- /.box-header -->
        <div class="box-body">
          <ul class="todo-list">
             {% for log in asset_log %}
            <li>
              <!-- drag handle -->
                  <span class="handle">
                   <small class="text-maroon">
                    <i class="glyphicon glyphicon-time"></i>
                    {{ log.add_time }}
                   </small>
                  </span>
              <!-- todo text -->
              <i class="fa fa-ellipsis-v"></i>
              <i class="fa fa-ellipsis-v"></i>
              <span>操作人：{{ log.operator }}</span>
              <i class="fa fa-ellipsis-v"></i>
              <i class="fa fa-ellipsis-v"></i>
              <span>{{ log.desc | safe }}</span>
            </li>
            {% endfor %}
          </ul>
        </div>
        <!-- /.box-body -->
      </div>
          <!-- /.box -->

    </section>

    <!-- /.content -->

{% endblock %}

{% block javascripts %}
  <script src="{% static 'js/plugins/layer/layer.js' %}"></script>
  <script type="text/javascript">
  	$(function() {
	    $('#ADM-ASSET').addClass('active');

	});
  	//返回
    $("#btnReturn").click(function(){
		history.back();
	});

    function doUpdate(id){
	var div=layer.open({
		type : 2,
		title : '修改设备信息',
		shadeClose : false,
    	maxmin : true,
		area : [ '800px', '580px' ],
		content : "{% url 'adm-asset:update' %}"+'?id='+id,
		end : function() {
			//oDataTable.ajax.reload();
            window.location.reload();

		}
	});
	layer.full(div)
}

//上传资料
  function doAssetUpload(id){
    var div=layer.open({
		type : 2,
		title : '上传资产文件',
		shadeClose : false,
        maxmin : true,
		area : [ '770px', '400px' ],
		content : [ "{% url 'adm-asset:upload' %}"+'?id='+id],
		end : function() {
            window.location.reload();

		}
	});
    layer.full(div)
}
</script>

{% endblock %}

templates/adm/asset/asset_upload.html
{% extends 'base-layer.html' %}
{% load staticfiles %}

{% block css %}
<link rel="stylesheet" href="{%static 'plugins/select2/select2.min.css' %}">
<link rel="stylesheet" href="{% static 'js/plugins/layer/skin/layer.css' %}">
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap-datetimepicker.min.css' %}">
<link rel="stylesheet" href="{% static 'plugins/fileinput/fileinput.css' %}">

{% endblock %}
{% block main %}
<div class="box box-danger">
	<form class="form-horizontal" id="addForm" method="post">
		{% csrf_token %}
        <div class="box-body">
          <fieldset>
            <div class="form-group has-feedback">
                <label class="col-sm-2 control-label">文件上传</label>
                <div class="col-sm-8">
                    <div class="file-loading">
                        <input id="file_content" name="file_content"  type="file" multiple="multiple"/>
                    </div>
                </div>
            </div>
          </fieldset>
            <fieldset>
                <div class="form-group has-feedback">
                    <label class="col-sm-2 control-label"></label>
                    <div class="col-sm-8">
                        <small class="text-red">只支持上传图片文件，最多上传4张，大小不得超过10M</small>
                    </div>
                </div>
            </fieldset>
        </div>
    </form>
</div>

{% endblock %}

{% block javascripts %}
<script src="{% static 'plugins/fileinput/fileinput.js' %}"></script>
<script src="{% static 'plugins/fileinput/zh.js' %}"></script>
<script type="text/javascript">


// 获取表单数据


//上传文件

$(document).on('ready', function() {
    $("#file_content").fileinput({
        language: "zh",
        showUpload: true,
        allowedFileExtensions: ["png", "jpg", "gif"],
        uploadUrl: "{% url 'adm-asset:upload' %}",
        uploadExtraData: {
            'csrfmiddlewaretoken': '{{ csrf_token }}',
            'asset': '{{ asset.id }}',
            'upload_user': '{{ request.user.name }}',
        },
        maxFileCount: 4,
        autoReplace: true,
        maxFileSize: 10240,
    });
});




</script>

{% endblock %}